name: getx_clean_architecture
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: 4.6.5
  get_storage: ^2.0.3
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/news_icon.svg
    - assets/images/bg_image.svg
    - assets/icons/
    - assets/locales/
